development:
  secret_token: "this_is_a_secret_token"
  secret_key_base: "MakeveliTupacShakur"

test:
  secret_token: "this_is_a_secret_token"
  secret_key_base: "MakeveliTupacShakur"

production:
  secret_token: "this_is_a_secret_token"
  secret_key_base: "MakeveliTupacShakur"
